name: publish-package

on:
  release:
    types:
      - published

permissions:
  id-token: write # Required for OIDC
  contents: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: Upgrade npm
        run: npm install -g npm@^11.5.1 # 11.5.1+ is required for OIDC trusted publishing (tokenless authentication)
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm run build
      - name: Publish to NPM
        run: npm publish
